//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEP_DATE
    {
        public long DATE_ID { get; set; }
        public System.DateTime FULL_DATE_DT { get; set; }
        public bool BUS_DAY_FL { get; set; }
        public int BUS_DAY_SUM_QY { get; set; }
        public string DAY_OF_WEEK_TX { get; set; }
        public byte DAY_OF_MONTH_NB { get; set; }
        public byte WEEK_OF_YEAR_NB { get; set; }
        public System.DateTime BSA_PAY_PERD_DT { get; set; }
        public short BSA_PAY_PERD_NB { get; set; }
        public System.DateTime BSU_PAY_PERD_DT { get; set; }
        public short BSU_PAY_PERD_NB { get; set; }
        public short MONTH_NB { get; set; }
        public string MONTH_TX { get; set; }
        public short CURR_MONTH_SEQ_NB { get; set; }
        public short QTR_NB { get; set; }
        public string QTR_TX { get; set; }
        public short YEAR_NB { get; set; }
        public short CURR_YEAR_SEQ_NB { get; set; }
        public string SEMIANNUAL_YEAR_TX { get; set; }
        public System.DateTime LAST_DATE_MO_DT { get; set; }
        public System.DateTime LAST_UPDT_DT { get; set; }
    }
}
