//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication14.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AEPDbContext : DbContext
    {
        public AEPDbContext()
            : base("name=AEPDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORY_DIM> CATEGORY_DIM { get; set; }
        public virtual DbSet<MEASURE_DIM> MEASURE_DIM { get; set; }
        public virtual DbSet<RPT_FREQ_DIM> RPT_FREQ_DIM { get; set; }
        public virtual DbSet<AEP_DATE> AEP_DATE { get; set; }
        public virtual DbSet<SCORECARD_FACT> SCORECARD_FACT { get; set; }
    }
}
