//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY_DIM
    {
        public decimal CATEGORY_ID { get; set; }
        public string CATEGORY_NAME { get; set; }
        public string CATEGORY_DESC { get; set; }
        public Nullable<System.DateTime> LAST_UPDT_DTTM { get; set; }
        public string LAST_UPDT_ID { get; set; }
    }
}
